"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { articles, latestArticles, permanentArticles } from "./lib/articles";

const currentDispatch = latestArticles[0];
const currentDispatchPath = currentDispatch.href;

const resources = [
  ["CompTIA CertMaster Platform", "Sign in to access assigned CompTIA CertMaster coursework, labs, and certification-preparation materials.", "Course Platform", "https://platform.comptia.org/"],
  ["CYBER.ORG", "Explore free cybersecurity curriculum, career resources, and learning programs designed for K–12 education.", "Curriculum", "https://cyber.org/"],
  ["CYBER.ORG Range", "Launch authorized browser-based virtual labs in a safe, isolated cyber range environment.", "Virtual Lab", "https://cyber.org/range"],
  ["CrypTool-Online", "Explore classic and modern cryptography through browser-based ciphers, cryptanalysis tools, and interactive demonstrations.", "Cryptography", "https://www.cryptool.org/en/cto/"],
  ["Simon Singh’s Black Chamber", "Learn the history and mechanics of classic ciphers through explanations, codebreaking guidance, and interactive tools.", "Cryptography", "https://www.simonsingh.net/The_Black_Chamber/chamberguide.html"],
  ["Mathematics of Cryptography", "Explore the mathematical foundations behind encryption, keys, and secure communication.", "Cryptography", "https://timothy815.github.io/Mathematics_of_Cryptography/index.html"],
  ["Modular Cryptography Workbench", "Experiment with modular arithmetic and the number systems that power modern cryptography.", "Interactive Lab", "https://timothy815.github.io/Modular_crypto_worksbench/"],
  ["Cipher Museum", "Investigate historical ciphers and the ideas that shaped the evolution of cryptography.", "Cryptography", "https://timothy815.github.io/cipher-museum/#/"],
];
const terms = [
  ["Academic honesty", "Accurately representing what you know, created, and contributed when submitting academic work.", "Ethics & learning"],
  ["Artificial intelligence (AI)", "Computer systems designed to perform tasks such as recognizing patterns, generating content, or making recommendations.", "AI & ethics"],
  ["Attack surface", "Every point where an unauthorized user could try to enter, affect, or extract data from a system.", "Risk"],
  ["Authentication", "The process of verifying that a user, device, or service is who or what it claims to be.", "Identity & access"],
  ["Authorization", "Permission to access a resource or perform an action after an identity has been established.", "Identity & access"],
  ["Availability", "The assurance that systems and data are accessible to authorized users when needed.", "CIA triad"],
  ["Business continuity", "Planning that keeps an organization’s essential operations functioning during and after a disruption.", "Resilience"],
  ["Confidentiality", "The protection of information from unauthorized access or disclosure.", "CIA triad"],
  ["Credential", "Information or evidence used to prove identity, such as a password, security key, or digital certificate.", "Identity & access"],
  ["Defense in depth", "Multiple, overlapping safeguards that prevent one failed control from exposing the whole system.", "Architecture"],
  ["Disaster recovery", "The process of restoring systems, data, and technology services after a serious disruption.", "Resilience"],
  ["Encryption", "Transforming readable data into a protected form that requires the correct key to interpret.", "Data protection"],
  ["False positive", "An alert that incorrectly identifies normal or harmless activity as suspicious or malicious.", "Security operations"],
  ["Feynman Technique", "A learning cycle of explaining an idea simply, finding gaps, studying them, and explaining the idea again.", "Learning strategy"],
  ["Firewall", "A security control that permits or blocks network traffic according to defined rules.", "Network security"],
  ["Hallucination (AI)", "Confident-sounding information generated by an AI system that is unsupported, invented, or incorrect.", "AI & ethics"],
  ["Impersonation", "Pretending to be a trusted person or authorized worker to gain access, information, or cooperation.", "Social engineering"],
  ["Incident response", "The organized process of detecting, containing, investigating, removing, and recovering from a security incident.", "Security operations"],
  ["Integrity", "The assurance that information and systems have not been altered improperly.", "CIA triad"],
  ["Least privilege", "Giving a user, process, or device only the access required to complete its task.", "Access control"],
  ["Log", "A time-ordered record of events produced by a system, application, device, or security tool.", "Security operations"],
  ["Malware", "Software intentionally designed to damage, disrupt, spy on, or gain unauthorized access to systems or data.", "Threats"],
  ["Multifactor authentication (MFA)", "Identity verification that requires two or more different kinds of evidence, such as a password and security key.", "Identity & access"],
  ["Network segmentation", "Dividing a network into controlled sections to limit access and reduce an attacker’s ability to move between systems.", "Network security"],
  ["Open-source intelligence (OSINT)", "Information collected and analyzed from publicly available sources such as websites, directories, and social media.", "Investigation"],
  ["Penetration testing", "An authorized, scoped security assessment that simulates attacks to identify and verify weaknesses.", "Security assessment"],
  ["Phishing", "Deceptive messages, commonly sent by email, that try to steal information or persuade someone to take an unsafe action.", "Social engineering"],
  ["Pretexting", "Creating a believable identity and story to justify a request and influence a target’s decision.", "Social engineering"],
  ["Private key", "A secret cryptographic value used to decrypt data, create digital signatures, or prove control of an identity.", "Cryptography"],
  ["Protégé effect", "The learning benefit gained when preparing to teach or taking responsibility for another learner’s understanding.", "Learning strategy"],
  ["Ransomware", "Malware that blocks access to systems or data, often through encryption, and demands payment for restoration.", "Threats"],
  ["Retrieval practice", "Strengthening learning by recalling and explaining information without looking at the original source.", "Learning strategy"],
  ["Risk management", "The process of identifying, assessing, prioritizing, and treating risks to an organization or system.", "Risk"],
  ["Security control", "A safeguard designed to prevent, detect, reduce, or respond to a security risk.", "Risk"],
  ["Shadow AI", "Use of AI tools that an organization has not approved, secured, or made able to monitor.", "AI & ethics"],
  ["Smishing (SMS phishing)", "Phishing delivered through text messages to pressure a target into clicking, replying, or revealing information.", "Social engineering"],
  ["Social engineering", "Influencing or deceiving people into revealing information, granting access, or taking an action that benefits an attacker.", "Social engineering"],
  ["Spoofing", "Falsifying source or identity information, such as a caller ID or sender address, to appear trustworthy.", "Deception"],
  ["Supply-chain attack", "Compromising a trusted vendor, software package, update, or service to reach its users or customers.", "Threats"],
  ["Threat", "A circumstance or actor with the potential to cause harm by exploiting a vulnerability.", "Risk"],
  ["Vishing (voice phishing)", "Phishing conducted through telephone calls or other voice services.", "Social engineering"],
  ["Vulnerability", "A weakness that could be exploited to compromise a system or its information.", "Risk"],
];

function Logo(){return <span className="logo" aria-hidden="true">CS</span>}

export default function Home(){
  const [query,setQuery]=useState("");
  const [filter,setFilter]=useState("All");
  const [wordQuery,setWordQuery]=useState("");
  const tags=["All",...new Set(resources.map(r=>r[2]))];
  const shownResources=filter==="All"?resources:resources.filter(r=>r[2]===filter);
  const shownTerms=terms.filter(t=>t.join(" ").toLowerCase().includes(wordQuery.toLowerCase()));
  const results=useMemo(()=>{
    const q=query.trim().toLowerCase(); if(!q)return [];
    return [...articles.map(article=>[article.kind,article.title,article.subtitle,article.href]),...resources.map(r=>["Resource",r[0],r[1],r[3]]),...terms.map(t=>["Word wall",t[0],t[1],"#word-wall"])].filter(r=>r.join(" ").toLowerCase().includes(q)).slice(0,6);
  },[query]);
  return <main id="top">
    <header><a className="brand" href="#top"><Logo/><span><strong>CYBER / CLASSROOM</strong><small>Student operations hub</small></span></a><nav aria-label="Primary navigation"><a href="#dispatch">Dispatch</a><a href="#resources">Resources</a><a href="#articles">Articles</a><a href="#word-wall">Word wall</a></nav><a className="portal" href="https://classroom.google.com/h/tv" target="_blank" rel="noreferrer">Class portal ↗</a></header>
    <section className="hero">
      <div className="hero-copy"><div className="online"><i/> Systems online · Classroom hub</div><p className="label">Cybersecurity operations // 2026–27</p><h1>Learn to think<br/>like a <em>defender.</em></h1><p className="lead">Your launch point for class updates, Security+ preparation, readings, technical resources, and the language of cybersecurity.</p><div className="actions"><Link className="button" href={currentDispatchPath}>Read the latest dispatch <b>→</b></Link><a href="#resources">Browse resource vault ↘</a></div>
        <div className="search-wrap"><label htmlFor="hub-search">Search the classroom hub</label><div className="search"><span>⌕</span><input id="hub-search" type="search" placeholder="Try “least privilege” or “Python”" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div>{query&&<div className="results" aria-live="polite">{results.length?results.map(r=><Link href={r[3]} key={r[0]+r[1]} onClick={()=>setQuery("")}><span>{r[0]}</span><strong>{r[1]}</strong><small>{r[2]}</small></Link>):<p>No matches yet. Try a broader term.</p>}</div>}</div>
      </div>
      <aside className="brief"><div className="brief-top"><span>Current briefing</span><b>ED. {String(currentDispatch.edition).padStart(2,"0")}</b></div><div className="brief-body"><small>{currentDispatch.publishedLabel}{" // Current brief"}</small><h2>{currentDispatch.title}</h2><p>{currentDispatch.subtitle}</p></div><dl><div><dt>Focus</dt><dd>{currentDispatch.subject}</dd></div><div><dt>Read</dt><dd>{currentDispatch.readTime}</dd></div><div><dt>Status</dt><dd className="ready">● Ready</dd></div></dl><Link href={currentDispatchPath}>Open full dispatch <span>→</span></Link></aside>
    </section>
    <div className="signal">{["01 // Security+ readiness", "02 // AP cybersecurity preparation", "03 // Defensive operations", "04 // Professional practice"].map(item => <span key={item}>{item}</span>)}</div>
    <section className="section dispatch" id="dispatch"><div className="section-head compact"><div><p className="label">01 // Classroom dispatch</p><h2>Ideas worth <em>examining.</em></h2></div></div><div className="dispatch-grid">
      <article className="dispatch-main"><div className="meta"><span>Latest edition</span><span>{currentDispatch.publishedLabel}</span><span>{currentDispatch.readTime}</span></div><h3>{currentDispatch.title}</h3><p>{currentDispatch.subtitle}</p><div className="steps"><div><b>01</b><p><strong>Read</strong>Follow the central idea from opening question to conclusion.</p></div><div><b>02</b><p><strong>Examine</strong>Test the evidence, assumptions, and examples for yourself.</p></div><div><b>03</b><p><strong>Discuss</strong>Use the closing questions to continue the investigation.</p></div></div><Link className="dark-button" href={currentDispatchPath}>Read full dispatch →</Link></article>
      <aside className="radar"><p className="label">On the radar</p><div className="latest-links">{latestArticles.map((article,index)=><Link href={article.href} key={article.slug}><span>{String(index+1).padStart(2,"0")}</span><p><strong>{article.title}</strong><small>{article.subject}{" // "}{article.publishedLabel}</small></p></Link>)}</div><div className="radar-links"><small>Permanent references</small>{permanentArticles.map(article=><Link href={article.href} key={article.slug}>{article.title}<span aria-hidden="true">→</span></Link>)}</div><Link href="/articles">Browse all past issues →</Link></aside>
    </div></section>
    <section className="section resources" id="resources"><div className="section-head light"><div><p className="label">02 // Resource vault</p><h2>The right tool,<br/><em>when you need it.</em></h2></div><p>Interactive cryptography tools and exhibits—organized for fast retrieval.</p></div><div className="filters" aria-label="Filter resources">{tags.map(tag=><button key={tag} className={filter===tag?"active":""} aria-pressed={filter===tag} onClick={()=>setFilter(tag)}>{tag}</button>)}</div><div className="resource-grid">{shownResources.map((r,i)=><article key={r[0]}><span className="number">{String(i+1).padStart(2,"0")}</span><small>{r[2]}</small><h3>{r[0]}</h3><p>{r[1]}</p><div><a className="resource-link" href={r[3]} target="_blank" rel="noreferrer"><span>Open resource</span><b aria-hidden="true">↗</b></a></div></article>)}</div></section>
    <section className="section readings" id="articles"><div className="section-head"><div><p className="label">03 // Past issues</p><h2>Published once.<br/><em>Useful anytime.</em></h2></div><p>Browse classroom dispatches and permanent course references by publication date or subject.</p></div><div className="reading-list">{articles.map((article,i)=><article key={article.slug}><span className="reading-no">0{i+1}</span><div><small>{article.subject}{" // "}{article.publishedLabel}</small><h3>{article.title}</h3><p>{article.subtitle}</p></div><Link href={article.href}>Read article →</Link></article>)}</div><Link className="archive-cta dark-button" href="/articles">Browse the full archive →</Link></section>
    <section className="section glossary" id="word-wall"><div className="glossary-intro"><p className="label">04 // Digital word wall</p><h2>Build your<br/><em>cyber vocabulary.</em></h2><p>Precise language leads to precise thinking. Search the terms we use in class and connect each one to its larger domain.</p><label className="word-search"><span className="sr-only">Search word wall</span><input type="search" placeholder="Search a term or domain…" value={wordQuery} onChange={e=>setWordQuery(e.target.value)}/><span>⌕</span></label><div className="alphabet">{"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map(l=><span className={terms.some(t=>t[0].startsWith(l))?"on":""} key={l}>{l}</span>)}</div></div><div className="terms" aria-live="polite">{shownTerms.map(t=><article key={t[0]}><div><h3>{t[0]}</h3><small>{t[2]}</small></div><p>{t[1]}</p></article>)}{!shownTerms.length&&<p>No matching terms. Try another keyword.</p>}</div></section>
    <section className="closing"><div><p className="label">Need a starting point?</p><h2>Check the latest dispatch.<br/>Then check the evidence.</h2></div><a className="dark-button" href="#top">Return to mission control ↑</a></section>
    <footer><a className="brand" href="#top"><Logo/><span><strong>CYBER / CLASSROOM</strong><small>Learn · Defend · Grow</small></span></a><p>Built for the students who will defend what comes next.</p><nav><a href="#dispatch">Dispatch</a><a href="#resources">Resources</a><a href="#articles">Articles</a><a href="#word-wall">Word wall</a></nav></footer>
  </main>
}
